# Generated by Django 3.1 on 2020-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_ship_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=100)),
                ('battle_name', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
